language: node_js
node_js:
- 6.1.0
services: mongodb
env:
  - TRAVIS_NODE_VERSION: 6.1.0
matrix:
  include:
    - env: TEST_DIR=server MONGO_URL=mongodb://localhost/agorask SHOULD_BUILD_IF_EXISTS=TRAVIS_BUILD_SERVER
      script: cd server && npm install && ENV=test npm run codecov
      before_deploy: cd $TRAVIS_BUILD_DIR/server
      deploy:
        api_key:
          secure: Ur+KY9x/T++N60xOqyza9CqnGTTCD4Wv2gC+WzpCUP6VF+YV8FOWidyK2cHvaTO8kvW1SGY4OR0tx7uEALkAgcwrUoNlcPmbibFEGBbbq8jAp2Ba2GUlmFJDj5xQngzgcNReC5Mso8CNQ19IfbMfabq455i/Q6Fc9w2yOwiO401fz2Mgnnpz2p2kYrtBPOkOn7S5Wj96/vcIrbrG4wCsjuPPJScoCYQJZAYOt/CUMLKY+iCiYN/61fSkezd/CaYgyrVvlFJeh90R49mSDB3G80RfVBijiiTDHe5mG2XAXUt51WzbQMVAHuQ8yWjU0VXjeh1ZZoToMcPJU2wBpXSLzw3bZSBsBR/jzs8mcQW+fXEB0wQCYgzvTheJcTeURHyX/J/QS8RE9/JA4yxbRTcTYNhxqsArXzGnrfLWaxnCdZuOt2rEn4FXkuL5vtK2Ms8Zzs8Pz8GyOF9ORb5DlfPPzFgjNCkB5WmgO+PWCJV/8Y/rHv1iB8aFrrUl//5E+2UGZ3q2WGmqVZ8HMHm/NWAaTQwXER+rSNnQJUpuIpoHmBSC95/N8pM/PW5nH0a/euxwAvZUmoGieZ3aBkPkCHkdPQiPyxVc60LvjdVgiWMK0rx6szwGnlKFLZqNFGc924IkKeZGdOw9AcJSoZoUO0qpoZ74TjOJYlHqsDE/6cVfuCs=
        provider: heroku
        app: agorask
        skip_cleanup: true
        on:
          branch: master
          condition: "$TEST_DIR = server"
    - env: TEST_DIR=mobile_app SHOULD_BUILD_IF_EXISTS=TRAVIS_BUILD_APP
      language: node_js
      script: cd mobile_app && npm install && ENV=test npm run codecov
    - language: android
      android:
        components:
          - build-tools-23.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - extra-android-support
      before_script: cd $TRAVIS_BUILD_DIR/mobile_app && npm install
      before_install: nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
      script: pwd && cd $TRAVIS_BUILD_DIR/mobile_app/android && ./gradlew assembleDebug
before_install: node -v && node $TRAVIS_BUILD_DIR/tools/travis/jobs_to_run.js
script: echo "Need to make integration tests (with the app connected to the server...)"
