version: 2
jobs:
  build:
    docker:
      - image: beevelop/android-nodejs:latest #node:7.7.2
    environment:
      KEYSTORE_ENCR_1: i6V6Ibes9jthI/QpymfqH3pWEqAVOwT7xohKL/ttL/CXpBnigPmvoUSe4mhblfcylLLPsukcfpQVwezMNeUV/VSyy3JQbimINmwuztnnMDtM4Sjz6DfNy8S60uqUB2yu1V8m5WCYeeXwXFuIe6iur3iqrpSRjpwbAGwOeVP/0B+NLe5ppIzZLSIjIRv0bQUl9lXmXE3Hcw8qmWP4wwRMHMfB9bPNc2UPa5BS5lUxzAI53c4/P/p9QpzRbY5D3T2EPWBnteYZxJH1IhWooU2wHSVpl0glw8YpvlTCb9K8b78JgKRone0HMG6YmRk8qDwIanJV/2AQKrcOyRccAPkxZ1OHNvaMtgLbzlmDLZ8+NJssuGLMOwxOtBnh9jSyrERruRp/GFgoyL8YW+ZEmPY5WlGg3MKYSMkawat30m/+9J1hw8rD5DrpVXTSclMTV2XzluSIst5DBk5Ewsk1QLbt5NVqL6Iz6/MJTVIluvPinNAWWW6LsTE87KjsNUV3rxyozCw5P0tUv3KciSUKU/+skC4h6FDKqDOp2yDLSPtXTxQfbaS6Tp6Wptw0yaxLtS0ExY1jz2BOoCL2LNsOptfiG7nglo2BwnIqJBkhzMoEwCRuKM6z1DSU4gLhpgL+JGxaPcjqZWuzI8Ynn1aZCZNCy2PAAJsSoWrybRUutYb9ryI=
      KEYSTORE_ENCR_2: ZxRCwfXRf64aCy4IeqGPs2Las/mggIFRubSlzj8vRAIwhDh6LGZNG0BWas6DAiMM3MIsrOgKiPzdjhb0pG4KlpKj6oDtWGlCzEup3NNz06KGs7GblfKQIaZ9MyU3YFACkeNMOobLvDuxBASO3UUWUkW7sH8IY5lqK5aa4Ppv2WyzC06sqYC2yazTYFcVSpNIxk6emIUuEsr1drXnOkJ0sU0BixojpNuC5FeC+HCHMLUxhmx+Ru7E4kZJ/EmbrADVNrLVV3d/jNBX2nrlQZ4JV3RDv0ZAIecQvM60JAz5/x4AjrI7nBCVPfkoQjCkvvyd2A2wJ5170ccvC8Px6eFEW7TmgraR46DcGyvh4K0EDwGQjEUnlJcBdGtXNjCyKsFazcJDThYnsOR96ofOWogpWaMEK9uCWR87C0/fzOq5MK28+WXfAqkJrQn2CVMxYJ7EQsyqQGoi3lbAbE65pb+es8QzLCMZPUaamXpxL8mtJrDRBQfG4KaC0t+ZW07lury40EUvinmATAbGzpewsPRaMDvV/e8Rvn/5olwX/sf/xTlylWhX4QJqHKHltnV5Zg3KPP6tAa0MzHzUBtm1RJbNSXKfwZ34g3s6zwcYheZfuyI8zxKyrGb6ZNBmwZLsIHVxBoZFcEG5QfgZj2qo3POPsiDKxiISdVbEQFWCC/bMRTo=
      KEYSTORE_ENCR_3: M5TU4Cb5R+6s7QOQQef4aAUXO8Cqii0pfsOkyE8EsDXOyIb5dv3w4DDPY/3Euqy0CqFXo7KnlS0oA0yUTGQGthChBxvOIwZLWgQ1diASXt3YxqJWQyKHGxXrkaWmCiM906YgvSN6g9VpRnpl6IOXHpKblbHLz0VMI44SxKfTwJkm6fvb9RoU+Khaxn8fTZspgnBdF/IQ87Mvp939fl1EQnHDyanDsDApHgj4lxoDLoLaXQCQ6TFk5jO1WM1U5Ih9OLOiOvFUydT9DHgD0IfgdGjj2D3vevqxozxjNDXdRO5TDg0Bfc7kHoLMdc3kiA5Y+tVoYR5ezQUH1VeDRetgUwfA6Q/elhGaNC60N1BzzQ1HD8IogQRO7IMnaqxBXUJzNI1ykilTE3bAVL82SCgX+0qEXjkmVi83b7HmIabuZdhFRJvGvw/JqodRj76/N5D3WXr5DLPOD5d6+JNtZuhbEvypJz76ixrHenAC4GuT7yfNq8HnTXBPJMj18ln+ZxKIrlpVm6rHch5eqsgnlbKVKthc9ohVuRKvf5wurhQ21REN14/lgSc6AwW/41ZAisLHrPyMejPENl7erWDVKr0t3iUjApTHgK66xLvHaZn8HPGj1bYF+TpKEL6+c7VaLUtrelXFSDnoRei8BXC6bk8d8gIgLiC7NEgZ7wIte/7+SHE=
      # ANDROID_SDK_HOME: /home/ubuntu/
      JAVA_OPTS: "-Xms518m -Xmx2048m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
      MONGO_URL: mongodb://localhost/agorask
    working_directory: ~/agorask
    parallelism: 4
    steps:
      - run:
          command: apt-get install git-all
      - checkout
      - run:
          name: Intall android dependencies
          command: |
            apt-get update && apt-get install -y default-jre
            ./tools/android_deps.sh
      - run:
          name: Install Dependencies
          command: |
            yarn
            cd ./tests/app/
            yarn
            cd ../../mobile_app/android
            ./gradlew assembleCiRelease --parallel
            cd ../..
            git remote add herokuTest git@heroku.com:agorask-test.git,
            git push herokuTest `git subtree split --prefix server HEAD`:master --force
      - run:
          name: Tests
          command: yarn test
      - run:
          name: Upload app to testobject
          command: |
              export APP_ID=$(curl -s -u "youennpennarun:$TESTOBJECT_API_KEY" \
              -X POST https://app.testobject.com:443/api/storage/upload \
              -H "Content-Type: application/octet-stream" \
              --data-binary @./mobile_app/android/app/build/outputs/apk/app-ciRelease.apk \
              ) && echo "export APP_ID=$APP_ID" >> ~/.circlerc;
              echo "Using app ID $APP_ID"
      - run:
          name: Integration tests
          command:  |
            cd ./tests/app
            yarn test